baseURL = "https://www.cmz.dev/"
languageCode = "en-us"
title = "Chris Zacny | Software Engineer"
theme = "tale"

[author]
  name = "Chris Zacny"
  url = "https://www.cmz.dev/"

[menu]
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  title = "Posts"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  title = "Tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 3
[[menu.main]]
  identifier = 'resume'
  name = 'Résumé'
  url = '/resume/'
  weight = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'
