baseURL = "https://www.cmz.dev/"
languageCode = "en-us"
title = "Chris Zacny's Site"
theme = "tale"

[menu]
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  title = "Posts"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 2
[[menu.main]]
  identifier = 'resume'
  name = 'Résumé'
  url = '/resume/'
  weight = 3
